/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (localhost, 12355).
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (localhost, 12355).

-------------------------------------------------------------------------------
train.py 154 <module>
mp.spawn(train, args=(world_size, 50, start_epoch, train_loader, simclr_model, optimizer, get_simclr_augmentation_pipeline(), get_simclr_augmentation_pipeline(type=2), temperature, checkpoint_dir), nprocs=world_size, join=True)

spawn.py 239 spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

spawn.py 197 start_processes
while not context.join():

spawn.py 160 join
raise ProcessRaisedException(msg, error_index, failed_process.pid)

torch.multiprocessing.spawn.ProcessRaisedException:


-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/work/cvcs_2023_group23/AIB/train.py", line 111, in train
    setup(rank, world_size)
  File "/work/cvcs_2023_group23/AIB/train.py", line 20, in setup
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 172, in _create_c10d_store
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
TimeoutError: The client socket has timed out after 1800s while trying to connect to (localhost, 12355).


-------------------------------------------------------------------------------
train.py 154 <module>
mp.spawn(train, args=(world_size, 50, start_epoch, train_loader, simclr_model, optimizer, get_simclr_augmentation_pipeline(), get_simclr_augmentation_pipeline(type=2), temperature, checkpoint_dir), nprocs=world_size, join=True)

spawn.py 239 spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

spawn.py 197 start_processes
while not context.join():

spawn.py 160 join
raise ProcessRaisedException(msg, error_index, failed_process.pid)

torch.multiprocessing.spawn.ProcessRaisedException:


-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/work/cvcs_2023_group23/AIB/train.py", line 111, in train
    setup(rank, world_size)
  File "/work/cvcs_2023_group23/AIB/train.py", line 20, in setup
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 172, in _create_c10d_store
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
TimeoutError: The client socket has timed out after 1800s while trying to connect to (localhost, 12355).

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3093901) of binary: /work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-11_20:44:09
  host      : ajeje.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3093902)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-11_20:44:09
  host      : ajeje.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3093901)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

-------------------------------------------------------------------------------
eval.py 96 <module>
train_features, train_labels = extract_features_and_labels(simclr_model, train_loader)

eval.py 64 extract_features_and_labels
output = model.base(images)

module.py 1501 _call_impl
return forward_call(*args, **kwargs)

container.py 217 forward
input = module(input)

module.py 1501 _call_impl
return forward_call(*args, **kwargs)

container.py 217 forward
input = module(input)

module.py 1501 _call_impl
return forward_call(*args, **kwargs)

resnet.py 158 forward
identity = self.downsample(x)

module.py 1501 _call_impl
return forward_call(*args, **kwargs)

container.py 217 forward
input = module(input)

module.py 1501 _call_impl
return forward_call(*args, **kwargs)

batchnorm.py 171 forward
return F.batch_norm(

functional.py 2450 batch_norm
return torch.batch_norm(

torch.cuda.OutOfMemoryError:
CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 10.75 GiB total capacity; 2.56 GiB already allocated; 297.62 MiB free; 4.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3101516 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 3101517) of binary: /work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/AIB/AIB_env_serial/AIB_env_serial/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
eval.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-11_20:46:08
  host      : ajeje.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3101517)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
