/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/AIB/train.py", line 147, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/AIB/train.py", line 147, in <module>
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/AIB/train.py", line 147, in <module>
    train_loader, eval_loader = get_data_loaders()  File "/work/cvcs_2023_group23/AIB/train.py", line 147, in <module>
        
    train_loader, eval_loader = get_data_loaders()
train_loader, eval_loader = get_data_loaders()  File "/work/cvcs_2023_group23/AIB/train.py", line 27, in get_data_loaders
train_loader, eval_loader = get_data_loaders()
  File "/work/cvcs_2023_group23/AIB/train.py", line 27, in get_data_loaders

  File "/work/cvcs_2023_group23/AIB/train.py", line 27, in get_data_loaders
      File "/work/cvcs_2023_group23/AIB/train.py", line 27, in get_data_loaders
    dataset = RxRx1Dataset(metadata_csv='metadata.csv', root_dir='/work/cvcs_2023_group23/AIB/data/rxrx1_v1.0', transform=transforms.Compose([transforms.CenterCrop(256), transforms.ToTensor(), transforms.Normalize(mean=(0.485, 0.456, 0.406), std = (0.229, 0.224, 0.225))]))    dataset = RxRx1Dataset(metadata_csv='metadata.csv', root_dir='/work/cvcs_2023_group23/AIB/data/rxrx1_v1.0', transform=transforms.Compose([transforms.CenterCrop(256), transforms.ToTensor(), transforms.Normalize(mean=(0.485, 0.456, 0.406), std = (0.229, 0.224, 0.225))]))
    dataset = RxRx1Dataset(metadata_csv='metadata.csv', root_dir='/work/cvcs_2023_group23/AIB/data/rxrx1_v1.0', transform=transforms.Compose([transforms.CenterCrop(256), transforms.ToTensor(), transforms.Normalize(mean=(0.485, 0.456, 0.406), std = (0.229, 0.224, 0.225))]))
  File "/work/cvcs_2023_group23/AIB/dataset.py", line 20, in __init__
  File "/work/cvcs_2023_group23/AIB/dataset.py", line 20, in __init__
dataset = RxRx1Dataset(metadata_csv='metadata.csv', root_dir='/work/cvcs_2023_group23/AIB/data/rxrx1_v1.0', transform=transforms.Compose([transforms.CenterCrop(256), transforms.ToTensor(), transforms.Normalize(mean=(0.485, 0.456, 0.406), std = (0.229, 0.224, 0.225))]))
  File "/work/cvcs_2023_group23/AIB/dataset.py", line 20, in __init__

  File "/work/cvcs_2023_group23/AIB/dataset.py", line 20, in __init__
                self.metadata_df = pd.read_csv(metadata_csv)
self.metadata_df = pd.read_csv(metadata_csv)
self.metadata_df = pd.read_csv(metadata_csv)self.metadata_df = pd.read_csv(metadata_csv)  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv


  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)            
return _read(filepath_or_buffer, kwds)return _read(filepath_or_buffer, kwds)return _read(filepath_or_buffer, kwds)  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read



  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)    
        parser = TextFileReader(filepath_or_buffer, **kwds)  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
parser = TextFileReader(filepath_or_buffer, **kwds)parser = TextFileReader(filepath_or_buffer, **kwds)


  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
      File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
self._engine = self._make_engine(f, self.engine)    
    self._engine = self._make_engine(f, self.engine)self._engine = self._make_engine(f, self.engine)
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self._engine = self._make_engine(f, self.engine)
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine

  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
      File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
self.handles = get_handle(
      File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    self.handles = get_handle(    self.handles = get_handle(
self.handles = get_handle(
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle

  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
                handle = open(
handle = open(
handle = open(
handle = open(
FileNotFoundErrorFileNotFoundErrorFileNotFoundErrorFileNotFoundError: : : : [Errno 2] No such file or directory: 'metadata.csv'[Errno 2] No such file or directory: 'metadata.csv'[Errno 2] No such file or directory: 'metadata.csv'[Errno 2] No such file or directory: 'metadata.csv'



WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 69578 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 69575) of binary: /work/cvcs_2023_group23/AIB/AIB_env/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/AIB/AIB_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-25_16:38:53
  host      : aimagelab-srv-10.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 69576)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-25_16:38:53
  host      : aimagelab-srv-10.ing.unimore.it
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 69577)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-25_16:38:53
  host      : aimagelab-srv-10.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 69575)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
